### ISSUE TITLE
Npm install not working on windows.

### ISSUE THREAD

**Issue by delaneyj** [khaled/react-coffee-express-template#1]
```
λ npm install                                                                                                   

> application-name@0.0.1 prepublish C:\Users\delaney\Desktop\react-coffee-express-template-master      
> $(npm bin)/bower install && $(npm bin)/gulp build                                                             

'$' is not recognized as an internal or external command,                                                       
operable program or batch file.                                                                                 

npm ERR! application-name@0.0.1 prepublish: `$(npm bin)/bower install && $(npm bin)/gulp build`                 
npm ERR! Exit status 1                                                                                          
npm ERR!                                                                                                        
npm ERR! Failed at the application-name@0.0.1 prepublish script.                                                
npm ERR! This is most likely a problem with the application-name package,                                       
npm ERR! not with npm itself.                                                                                   
npm ERR! Tell the author that this fails on your system:                                                        
npm ERR!     $(npm bin)/bower install && $(npm bin)/gulp build                                                  
npm ERR! You can get their info via:                                                                            
npm ERR!     npm owner ls application-name                                                                      
npm ERR! There is likely additional logging output above.                                                       
npm ERR! System Windows_NT 6.2.9200                                                                             
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\n
pm\\bin\\npm-cli.js" "install"                                                                                  
npm ERR! cwd C:\Users\delaney\Desktop\react-coffee-express-template-master                             
npm ERR! node -v v0.10.35                                                                                       
npm ERR! npm -v 1.4.28                                                                                          
npm ERR! code ELIFECYCLE                                                                                        
npm ERR!                                                                                                        
npm ERR! Additional logging details can be found in:                                                            
npm ERR!     C:\Users\delaney\Desktop\react-coffee-express-template-master\npm-debug.log               
npm ERR! not ok code 0                                                                                          

C:\Users\delaney\Desktop\react-coffee-express-template-master                                          
λ                                                                                                               
```

normal node/gulp commands work (my path is fine).  My guess is this wasn't ever tested on a windows machine.  Let me know what I can do to help test.

**Comment by delaneyj** [comment]
Changing the "prepublish" to `prepublish": "bower install && gulp build"` helps but then dies later at 

```
> bower install && gulp build


C:\Users\delaney\Desktop\react-coffee-express-template-master\gulpfile.coffee:1
tion (exports, require, module, __filename, __dirname) { gulp = require 'gulp'
                                                                        ^^^^^^
SyntaxError: Unexpected string
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (C:\Users\delaney\Desktop\react-coffee-express-template-master\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\delaney\Desktop\react-coffee-express-template-master\node_modules\gulp\node_modules\liftoff\index.js:159:12)
    at module.exports (C:\Users\delaney\Desktop\react-coffee-express-template-master\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.launch (C:\Users\delaney\Desktop\react-coffee-express-template-master\node_modules\gulp\node_modules\liftoff\index.js:152:5)

npm ERR! application-name@0.0.1 prepublish: `bower install && gulp build`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the application-name@0.0.1 prepublish script.
npm ERR! This is most likely a problem with the application-name package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls application-name
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\delaney\Desktop\react-coffee-express-template-master
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\delaney\Desktop\react-coffee-express-template-master\npm-debug.log
npm ERR! not ok code 0

```
